### ISSUE TITLE
Spark Application Not Terminated

### ISSUE THREAD

**Issue by ghost** [PredictionIO/template-scala-parallel-universal-recommendation#36]
The deployed engine doesn't use Spark, but a Spark application is still launched and remains running when the engine is deployed. The application can be killed without consequence (just error messages), but ideally it would do this automatically, or even better, not require Spark to deploy at all.

**Comment by pferrel** [comment]
Fixed in v0.3.0, you can pick it up from https://github.com/actionml/template-scala-parallel-universal-recommendation/tree/v0.3.0 https://github.com/actionml/template-scala-parallel-universal-recommendation/tree/v0.3.0 

On Feb 20, 2016, at 9:39 AM, Justin Ramos notifications@github.com wrote:

The deployed engine doesn't use Spark, but a Spark application is still launched and remains running when the engine is deployed. The application can be killed without consequence (just error messages), but ideally it would do this automatically, or even better, not require Spark to deploy at all.

**Comment by pferrel** [comment]
notice it's not in the PIO repos yet

**Comment by ghost** [comment]
Does that remove the need to have a Spark master running when deploying, or does it just prevent the Spark application from running?

**Comment by ghost** [comment]
Even with v0.3.0, the Spark application starts and continues running.

**Comment by tobilg** [comment]
I noticed the same behavior. The Spark app keeps running...

**Comment by pferrel** [comment]
The latest version creates an ephemeral context and will use master = local if you tell it to so no context is created on your cluster. You can pass in the master with `pio train -- --master local` I think, check the spark-submit cli and don't forget the blank `--` as a separator.

BTW, sorry to miss these questions. If you post them to the root repo [here](https://github.com/actionml/template-scala-parallel-universal-recommendation) you'll get noticed quicker

**Comment by ghost** [comment]
@pferrel -- that fixed it. Many thanks.
